src/Entity/Session.php
<?php

namespace App\Entity;

use App\Repository\SessionRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: SessionRepository::class)]
class Session
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\ManyToOne(targetEntity: Promotion::class, inversedBy: 'sessions')]
    #[ORM\JoinColumn(nullable: false)]
    private $promotion;

    #[ORM\Column(type: 'date')]
    private $date_debut;

    #[ORM\Column(type: 'date')]
    private $date_fin;

    #[ORM\Column(type: 'string', length: 255)]
    private $nom;

    #[ORM\ManyToMany(targetEntity: Formateur::class, inversedBy: 'sessions')]
    private $formateur;

    #[ORM\ManyToMany(targetEntity: Salle::class, mappedBy: 'session')]
    private $salles;



    public function __construct()
    {
        $this->formateur = new ArrayCollection();
        $this->salles = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPromotion(): ?Promotion
    {
        return $this->promotion;
    }

    public function setPromotion(?Promotion $promotion): self
    {
        $this->promotion = $promotion;

        return $this;
    }


    public function getDateDebut(): ?\DateTimeInterface
    {
        return $this->date_debut;
    }

    public function setDateDebut(\DateTimeInterface $date_debut): self
    {
        $this->date_debut = $date_debut;

        return $this;
    }

    public function getDateFin(): ?\DateTimeInterface
    {
        return $this->date_fin;
    }

    public function setDateFin(\DateTimeInterface $date_fin): self
    {
        $this->date_fin = $date_fin;

        return $this;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    /**
     * @return Collection<int, Formateur>
     */
    public function getFormateur(): Collection
    {
        return $this->formateur;
    }

    public function addFormateur(Formateur $formateur): self
    {
        if (!$this->formateur->contains($formateur)) {
            $this->formateur[] = $formateur;
        }

        return $this;
    }

    public function removeFormateur(Formateur $formateur): self
    {
        $this->formateur->removeElement($formateur);

        return $this;
    }

    /**
     * @return Collection<int, Salle>
     */
    public function getSalles(): Collection
    {
        return $this->salles;
    }

    public function addSalle(Salle $salle): self
    {
        if (!$this->salles->contains($salle)) {
            $this->salles[] = $salle;
            $salle->addSession($this);
        }

        return $this;
    }

    public function removeSalle(Salle $salle): self
    {
        if ($this->salles->removeElement($salle)) {
            $salle->removeSession($this);
        }

        return $this;
    }

}

src/Form/SessionType.php
<?php

namespace App\Form;

use App\Entity\Session;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class SessionType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('date_debut',  DateType::class, [
                'label' => 'Date de debut',
                'widget' => 'single_text',
                'format' => 'yyyy-MM-dd',
                'attr' => [
                    'class' => 'js-datepicker',
                    'data-provide' => 'datepicker',
                    'data-date-format' => 'yyyy-mm-dd',
                    'data-date-language' => 'fr',
                    'data-date-autoclose' => 'true',
                ],
            ])
            ->add('date_fin',  DateType::class, [
                'label' => 'Date de debut',
                'widget' => 'single_text',
                'format' => 'yyyy-MM-dd',
                'attr' => [
                    'class' => 'js-datepicker',
                    'data-provide' => 'datepicker',
                    'data-date-format' => 'yyyy-mm-dd',
                    'data-date-language' => 'fr',
                    'data-date-autoclose' => 'true',
                ],
            ])
            ->add('nom')
            ->add('promotion')
            ->add('salles')
            ->add('formateur')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Session::class,
        ]);
    }
}

src/Controller/SessionController.php
<?php

namespace App\Controller;

use App\Entity\Session;
use App\Form\SessionType;
use App\Repository\SessionRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/session')]
class SessionController extends AbstractController
{
    #[Route('/', name: 'app_session_index', methods: ['GET'])]
    public function index(SessionRepository $sessionRepository): Response
    {
        return $this->render('session/index.html.twig', [
            'sessions' => $sessionRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_session_new', methods: ['GET', 'POST'])]
    public function new(Request $request, SessionRepository $sessionRepository): Response
    {
        $session = new Session();
        $form = $this->createForm(SessionType::class, $session);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $sessionRepository->add($session, true);

            return $this->redirectToRoute('app_session_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('session/new.html.twig', [
            'session' => $session,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_session_show', methods: ['GET'])]
    public function show(Session $session): Response
    {
        return $this->render('session/show.html.twig', [
            'session' => $session,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_session_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Session $session, SessionRepository $sessionRepository): Response
    {
        $form = $this->createForm(SessionType::class, $session);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $sessionRepository->add($session, true);

            return $this->redirectToRoute('app_session_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('session/edit.html.twig', [
            'session' => $session,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_session_delete', methods: ['POST'])]
    public function delete(Request $request, Session $session, SessionRepository $sessionRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$session->getId(), $request->request->get('_token'))) {
            $sessionRepository->remove($session, true);
        }

        return $this->redirectToRoute('app_session_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/session/_delete_form.html.twig
<form method="post" action="{{ path('app_session_delete', {'id': session.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ session.id) }}">
    <button class="btn">Delete</button>
</form>

templates/session/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/session/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Session{% endblock %}

{% block body %}
    <h1 id="page_title">Édition</h1>

    {{ include('session/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_session_index') }}">back to list</a>

    {{ include('session/_delete_form.html.twig') }}
{% endblock %}

templates/session/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Session index{% endblock %}

{% block body %}
    <h1 id="page_title">Session</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Date_debut</th>
                <th>Date_fin</th>
                <th>Nom</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for session in sessions %}
            <tr>
                <td>{{ session.id }}</td>
                <td>{{ session.dateDebut ? session.dateDebut|date('Y-m-d') : '' }}</td>
                <td>{{ session.dateFin ? session.dateFin|date('Y-m-d') : '' }}</td>
                <td>{{ session.nom }}</td>
                <td>
                    <a href="{{ path('app_session_show', {'id': session.id}) }}">show</a>
                    <a href="{{ path('app_session_edit', {'id': session.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_session_new') }}">Create new</a>
{% endblock %}

templates/session/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Session{% endblock %}

{% block body %}
    <h1 id="page_title">Nouvelle session</h1>

    {{ include('session/_form.html.twig') }}

    <a href="{{ path('app_session_index') }}">back to list</a>
{% endblock %}

templates/session/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Session{% endblock %}

{% block body %}
    <h1 id="page_title"><Édition></Édition></h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ session.id }}</td>
            </tr>
            <tr>
                <th>Date_debut</th>
                <td>{{ session.dateDebut ? session.dateDebut|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Date_fin</th>
                <td>{{ session.dateFin ? session.dateFin|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Nom</th>
                <td>{{ session.nom }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_session_index') }}">back to list</a>

    <a href="{{ path('app_session_edit', {'id': session.id}) }}">edit</a>

    {{ include('session/_delete_form.html.twig') }}
{% endblock %}