src/Entity/Candidat.php
<?php

namespace App\Entity;

use App\Repository\CandidatRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: CandidatRepository::class)]
class Candidat
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 255)]
    private $nom;

    #[ORM\Column(type: 'string', length: 255)]
    private $prenom;

    #[ORM\Column(type: 'string', length: 255)]
    private $email_contact;

    #[ORM\Column(type: 'string', length: 255)]
    /**
     * @Assert\Regex(
     *     pattern = "/^(?:(?:\+|00)33[\s.-]{0,3}(?:\(0\)[\s.-]{0,3})?|0)[1-9](?:(?:[\s.-]?\d{2}){4}|\d{2}(?:[\s.-]?\d{3}){2})$/",
     *     message = "Le numéro de téléphone {{ value }} est incorrect. Son format doit être en +33 ou commencer par 0"
     * )
     */
    private $numero_tel;

    #[ORM\ManyToOne(targetEntity: Promotion::class, inversedBy: 'candidats')]
    #[ORM\JoinColumn(nullable: false)]
    private $promotion;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getEmailContact(): ?string
    {
        return $this->email_contact;
    }

    public function setEmailContact(string $email_contact): self
    {
        $this->email_contact = $email_contact;

        return $this;
    }

    public function getNumeroTel(): ?string
    {
        return $this->numero_tel;
    }

    public function setNumeroTel(string $numero_tel): self
    {
        $this->numero_tel = $numero_tel;

        return $this;
    }

    public function getPromotion(): ?Promotion
    {
        return $this->promotion;
    }

    public function setPromotion(?Promotion $promotion): self
    {
        $this->promotion = $promotion;

        return $this;
    }
}

src/Form/CandidatType.php
<?php

namespace App\Form;

use App\Entity\Candidat;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\TelType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;


class CandidatType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nom')
            ->add('prenom')
            ->add('email_contact', EmailType::class, [
                'required' => true,
            ])
            ->add('numero_tel', TelType::class, [
                'required' => true,
            ])
            ->add('promotion')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Candidat::class,
        ]);
    }
}

src/Controller/CandidatController.php
<?php

namespace App\Controller;

use App\Entity\Candidat;
use App\Form\CandidatType;
use App\Repository\CandidatRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/candidat')]
class CandidatController extends AbstractController
{
    #[Route('/', name: 'app_candidat_index', methods: ['GET'])]
    public function index(CandidatRepository $candidatRepository): Response
    {
        return $this->render('candidat/index.html.twig', [
            'candidats' => $candidatRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_candidat_new', methods: ['GET', 'POST'])]
    public function new(Request $request, CandidatRepository $candidatRepository): Response
    {
        $candidat = new Candidat();
        $form = $this->createForm(CandidatType::class, $candidat);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $candidatRepository->add($candidat, true);

            return $this->redirectToRoute('app_candidat_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('candidat/new.html.twig', [
            'candidat' => $candidat,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_candidat_show', methods: ['GET'])]
    public function show(Candidat $candidat): Response
    {
        return $this->render('candidat/show.html.twig', [
            'candidat' => $candidat,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_candidat_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Candidat $candidat, CandidatRepository $candidatRepository): Response
    {
        $form = $this->createForm(CandidatType::class, $candidat);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $candidatRepository->add($candidat, true);

            return $this->redirectToRoute('app_candidat_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('candidat/edit.html.twig', [
            'candidat' => $candidat,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_candidat_delete', methods: ['POST'])]
    public function delete(Request $request, Candidat $candidat, CandidatRepository $candidatRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$candidat->getId(), $request->request->get('_token'))) {
            $candidatRepository->remove($candidat, true);
        }

        return $this->redirectToRoute('app_candidat_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/candidat/_delete_form.html.twig
<form method="post" action="{{ path('app_candidat_delete', {'id': candidat.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ candidat.id) }}">
    <button class="btn btn-danger">Supprimer</button>
</form>

templates/candidat/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/candidat/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Candidat{% endblock %}

{% block body %}
    <h1 id="page_title">Édition</h1>

    {{ include('candidat/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_candidat_index') }}">Retour à la liste</a>

    {{ include('candidat/_delete_form.html.twig') }}
{% endblock %}

templates/candidat/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Candidat index{% endblock %}

{% block body %}
    <h1 id="page_title">Candidat</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Nom</th>
                <th>Prenom</th>
                <th>Email_contact</th>
                <th>Numero_tel</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for candidat in candidats %}
            <tr>
                <td>{{ candidat.id }}</td>
                <td>{{ candidat.nom }}</td>
                <td>{{ candidat.prenom }}</td>
                <td>{{ candidat.emailContact }}</td>
                <td>{{ candidat.numeroTel }}</td>
                <td>
                    <a href="{{ path('app_candidat_show', {'id': candidat.id}) }}">show</a>
                    <a href="{{ path('app_candidat_edit', {'id': candidat.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_candidat_new') }}">Create new</a>
{% endblock %}

templates/candidat/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Candidat{% endblock %}

{% block body %}
    <h1 id="page_title">Nouveau candidat</h1>

    {{ include('candidat/_form.html.twig') }}

    <a href="{{ path('app_candidat_index') }}">Retour à la liste</a>
{% endblock %}

templates/candidat/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Candidat{% endblock %}

{% block body %}
    <h1 id="page_title">Édition</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ candidat.id }}</td>
            </tr>
            <tr>
                <th>Nom</th>
                <td>{{ candidat.nom }}</td>
            </tr>
            <tr>
                <th>Prenom</th>
                <td>{{ candidat.prenom }}</td>
            </tr>
            <tr>
                <th>Email_contact</th>
                <td>{{ candidat.emailContact }}</td>
            </tr>
            <tr>
                <th>Numero_tel</th>
                <td>{{ candidat.numeroTel }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_candidat_index') }}">Retour à la liste</a>

    <a href="{{ path('app_candidat_edit', {'id': candidat.id}) }}">edit</a>

    {{ include('candidat/_delete_form.html.twig') }}
{% endblock %}